# Generated by Django 2.1.7 on 2019-03-02 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardEarningRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_everything', models.IntegerField(default=1)),
                ('points_travel', models.IntegerField(default=1)),
                ('points_flights', models.IntegerField(default=1)),
                ('points_us_dining', models.IntegerField(default=1)),
                ('points_gas', models.IntegerField(default=1)),
                ('points_grocery', models.IntegerField(default=1)),
                ('points_amazon', models.IntegerField(default=1)),
                ('points_hotel', models.IntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditcards.Card')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creditcards.Reward')),
            ],
        ),
    ]
