# Generated by Django 2.1.7 on 2019-03-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditcards', '0002_rewardearningrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardearningrate',
            name='reward',
        ),
    ]
